# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  dev:
    desc: Run live-reload dev mode
    vars:
      GIT_TAG:
        sh: git describe --tags --always 2>/dev/null || echo dev
    cmds:
      - wails dev -tags webkit2_41 -ldflags "-X 'StreamFighter/internal.Version={{.GIT_TAG}}'"

  build:
    desc: Build production binary
    vars:
      GIT_TAG:
        sh: git describe --tags --always 2>/dev/null || echo dev
    cmds:
      - wails build -tags webkit2_41 -ldflags "-X 'StreamFighter/internal.Version={{.GIT_TAG}}'"

  format:
    desc: Run formatter across files
    cmds:
      - bunx prettier ./frontend/src --write
      - gofmt -w . ./internal
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
