// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetsBaseURL() {
  return window['go']['internal']['App']['AssetsBaseURL']();
}

export function BetweenOverlayURL() {
  return window['go']['internal']['App']['BetweenOverlayURL']();
}

export function ClearState() {
  return window['go']['internal']['App']['ClearState']();
}

export function DeleteCasterPreset(arg1) {
  return window['go']['internal']['App']['DeleteCasterPreset'](arg1);
}

export function DeletePlayerPreset(arg1) {
  return window['go']['internal']['App']['DeletePlayerPreset'](arg1);
}

export function FetchStartggSets(arg1) {
  return window['go']['internal']['App']['FetchStartggSets'](arg1);
}

export function FetchStartggTournament(arg1) {
  return window['go']['internal']['App']['FetchStartggTournament'](arg1);
}

export function GameOverlayURL() {
  return window['go']['internal']['App']['GameOverlayURL']();
}

export function GetConfig() {
  return window['go']['internal']['App']['GetConfig']();
}

export function GetSecrets() {
  return window['go']['internal']['App']['GetSecrets']();
}

export function GetState() {
  return window['go']['internal']['App']['GetState']();
}

export function ListCasterPresets() {
  return window['go']['internal']['App']['ListCasterPresets']();
}

export function ListGames() {
  return window['go']['internal']['App']['ListGames']();
}

export function ListPlayerPresets() {
  return window['go']['internal']['App']['ListPlayerPresets']();
}

export function ReloadGames() {
  return window['go']['internal']['App']['ReloadGames']();
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['internal']['App']['ResizeWindow'](arg1, arg2);
}

export function SaveCasterPreset(arg1) {
  return window['go']['internal']['App']['SaveCasterPreset'](arg1);
}

export function SavePlayerPreset(arg1) {
  return window['go']['internal']['App']['SavePlayerPreset'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['internal']['App']['SetConfig'](arg1);
}

export function SetSecrets(arg1) {
  return window['go']['internal']['App']['SetSecrets'](arg1);
}

export function SetState(arg1) {
  return window['go']['internal']['App']['SetState'](arg1);
}

export function Update() {
  return window['go']['internal']['App']['Update']();
}
