// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';

export function AssetsBaseURL():Promise<string>;

export function BetweenOverlayURL():Promise<string>;

export function ClearState():Promise<internal.StreamState>;

export function DeleteCasterPreset(arg1:string):Promise<void>;

export function DeletePlayerPreset(arg1:string):Promise<void>;

export function FetchStartggSets(arg1:string):Promise<internal.StartggSetsResult>;

export function FetchStartggTournament(arg1:string):Promise<internal.StartggTournament>;

export function GameOverlayURL():Promise<string>;

export function GetConfig():Promise<internal.OutputConfig>;

export function GetSecrets():Promise<internal.Secrets>;

export function GetState():Promise<internal.StreamState>;

export function ListCasterPresets():Promise<Array<internal.CasterPreset>>;

export function ListGames():Promise<Array<internal.GamePack>>;

export function ListPlayerPresets():Promise<Array<internal.PlayerPreset>>;

export function ReloadGames():Promise<Array<internal.GamePack>>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function SaveCasterPreset(arg1:internal.CasterPreset):Promise<internal.CasterPreset>;

export function SavePlayerPreset(arg1:internal.PlayerPreset):Promise<internal.PlayerPreset>;

export function SetConfig(arg1:internal.OutputConfig):Promise<void>;

export function SetSecrets(arg1:internal.Secrets):Promise<void>;

export function SetState(arg1:internal.StreamState):Promise<void>;

export function Update():Promise<void>;
