// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetsBaseURL() {
  return window['go']['main']['App']['AssetsBaseURL']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function OverlayURL() {
  return window['go']['main']['App']['OverlayURL']();
}

export function ReloadGames() {
  return window['go']['main']['App']['ReloadGames']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function SetState(arg1) {
  return window['go']['main']['App']['SetState'](arg1);
}

export function Update() {
  return window['go']['main']['App']['Update']();
}
