// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AssetsBaseURL():Promise<string>;

export function GetConfig():Promise<main.OutputConfig>;

export function GetState():Promise<main.StreamState>;

export function ListGames():Promise<Array<main.GamePack>>;

export function OverlayURL():Promise<string>;

export function ReloadGames():Promise<Array<main.GamePack>>;

export function SetConfig(arg1:main.OutputConfig):Promise<void>;

export function SetState(arg1:main.StreamState):Promise<void>;

export function Update():Promise<void>;
